apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-service

spec:
  replicas: 1

  selector:
    matchLabels:
      app: customer-service

  template:
    metadata:
      labels:
        app: customer-service

    spec:
      containers:
        - name: customer-service
          image: customer-service:latest
          imagePullPolicy: Never

          ports:
            - containerPort: 8081

          env:
            - name: DB_URL
              value: jdbc:mysql://customer-db:3306/customerdb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC

            - name: DB_USERNAME
              value: root

            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: customer-secret
                  key: db-password

            - name: BOOKING_SERVICE_URL
              value: http://booking-service:8080

            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: customer-secret
                  key: jwt-secret

            - name: ADMIN_USERNAME
              valueFrom:
                secretKeyRef:
                  name: customer-secret
                  key: admin-username

            - name: ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: customer-secret
                  key: admin-password
