apiVersion: v1
kind: Secret
metadata:
  name: booking-secret

type: Opaque

stringData:
  db-password: bookingpassword
  jwt-secret: my-super-secret-jwt-key-that-is-long-enough-123456
  admin-username: admin
  admin-password: admin123